services:
  mongo:
    image: mongo:7
    container_name: vetsalud-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: vetsalud-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password123
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  mongo_data:
  neo4j_data:
  neo4j_logs:
